package com.trustid.common.enums;

public enum AuditAction {
    REGISTER,
    VERIFY_EMAIL,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    FORGOT_PASSWORD,
    RESET_PASSWORD,
    CREATE_IDENTITY,
    UPDATE_IDENTITY,
    UPLOAD_DOCUMENT,
    UPDATE_DOCUMENT,
    DELETE_DOCUMENT,
    SUBMIT_VERIFICATION,
    APPROVE_VERIFICATION,
    REJECT_VERIFICATION,
    REQUEST_RESUBMISSION,
    GENERATE_QR,
    CREATE_SHARE_LINK,
    REVOKE_SHARE_LINK,
    VIEW_PUBLIC_VERIFICATION
}
