version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: trustid_db
    environment:
      POSTGRES_DB: trustid_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: trustid_mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    restart: unless-stopped

volumes:
  pgdata:
